language: r

dist: trusty

jdk:
  - openjdk8

sudo: false

cache:
  packages: true

warnings_are_errors: true

script:
- |
  R CMD build .
  R CMD check  --no-tests  *tar.gz
  cd tests
  export NOT_CRAN=true
  travis_wait 10 Rscript ../.travis.R
  sleep 2
