language: r

cache:
  packages: true

warnings_are_errors: true

jdk:
  - oraclejdk8

script:
- |
  R CMD build .
  R CMD check  --no-tests  *tar.gz 
  cd tests
  export NOT_CRAN=true
  travis_wait 35 Rscript ../.travis.R
  sleep 2
